kind: Deployment
apiVersion: apps/v1
metadata:
  name: lowdefy
  labels:
    app: lowdefy
    k8s-app: lowdefy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lowdefy
      k8s-app: lowdefy
  template:
    metadata:
      name: lowdefy
      labels:
        app: lowdefy
        k8s-app: lowdefy
    spec:
      volumes:
        - name: lowdefy-build-storage
          persistentVolumeClaim:
            claimName: lowdefy-build-pvc
      containers:
        - name: lowdefy
          image: imvegeta/img_lowdefy
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: LOWDEFY_SERVER_PORT
              value: '3000'
            - name: LOWDEFY_SERVER_CONFIGURATION_PATH
              value: /home/node/lowdefy/volumes/build
          resources: {}
          volumeMounts:
            - name: lowdefy-build-storage
              mountPath: /home/node/lowdefy/volumes/build
          imagePullPolicy: Always
          securityContext:
            privileged: false
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
