kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lowdefy-build-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  volumeName: lowdefy-build-pv
  storageClassName: manual
  volumeMode: Filesystem
