kind: Deployment
apiVersion: apps/v1
metadata:
  name: lowdefy-git-sync-example
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lowdefy-git-sync-example
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lowdefy-git-sync-example
    spec:
      volumes:
        - name: content-from-git
          emptyDir: {}
      initContainers:
        - name: git-sync
          image: 'k8s.gcr.io/git-sync/git-sync:v3.2.2'
          envFrom:
            - configMapRef:
                name: lowdefy-gitsync
            - secretRef:
                name: lowdefy-secrets
          resources: {}
          volumeMounts:
            - name: content-from-git
              mountPath: /git
          imagePullPolicy: IfNotPresent
      containers:
        - name: lowdefy
          image: imvegeta/img_lowdefy
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: LOWDEFY_SERVER_PORT
              value: '3000'
            - name: LOWDEFY_SERVER_CONFIGURATION_PATH
              value: /home/node/lowdefy/volumes/build
          resources: {}
          volumeMounts:
            - name: content-from-git
              readOnly: true
              mountPath: /home/node/lowdefy/volumes/
          imagePullPolicy: Always
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
