kind: Service
apiVersion: v1
metadata:
  name: lowdefy-git-sync-example
  namespace: default
  labels:
    app: lowdefy-git-sync-example
spec:
  ports:
    - name: 3000-3000
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30864
  selector:
    app: lowdefy-git-sync-example
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
